/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#fcf8fa",
        "on-secondary-fixed-variant": "#005049",
        "on-tertiary-container": "#98805d",
        "tertiary-container": "#271901",
        "surface-container-high": "#eae7e9",
        "on-primary-container": "#7c839b",
        "secondary": "#006a61",
        "surface-bright": "#fcf8fa",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#131b2e",
        "surface-container": "#f0edef",
        "surface-variant": "#e4e2e4",
        "on-surface-variant": "#45464d",
        "primary-fixed-dim": "#bec6e0",
        "surface": "#fcf8fa",
        "secondary-container": "#86f2e4",
        "secondary-fixed": "#89f5e7",
        "on-primary-fixed-variant": "#3f465c",
        "on-secondary": "#ffffff",
        "primary-container": "#131b2e",
        "inverse-surface": "#303032",
        "outline": "#76777d",
        "on-background": "#1b1b1d",
        "primary": "#000000",
        "surface-container-highest": "#e4e2e4",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#dcd9db",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#6bd8cb",
        "tertiary-fixed-dim": "#dec29a",
        "on-tertiary-fixed-variant": "#574425",
        "on-secondary-container": "#006f66",
        "on-secondary-fixed": "#00201d",
        "tertiary-fixed": "#fcdeb5",
        "inverse-on-surface": "#f3f0f2",
        "on-error": "#ffffff",
        "outline-variant": "#c6c6cd",
        "surface-container-low": "#f6f3f5",
        "on-tertiary-fixed": "#271901",
        "on-surface": "#1b1b1d",
        "error-container": "#ffdad6",
        "inverse-primary": "#bec6e0",
        "surface-tint": "#565e74",
        "tertiary": "#000000",
        "primary-fixed": "#dae2fd",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "16px",
        unit: "4px",
        "container-padding": "24px",
        "card-gap": "20px",
      },
      fontFamily: {
        "body-md": ["Geist", "sans-serif"],
        "tabular-nums": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        display: ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "tabular-nums": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        display: [
          "36px",
          {
            lineHeight: "44px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "headline-lg": [
          "28px",
          {
            lineHeight: "36px",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "label-md": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.01em",
            fontWeight: "500",
          },
        ],
      },
    },
  },
  plugins: [],
};
